load("//scala-android:scala-android.bzl", "scala_android_library")

scala_android_library(
    name = "typed-resources",
    generate_typed_resources = False,
    srcs = glob(["src/main/scala/**/*.scala"]),
    visibility = ["//visibility:public"],
)
